[connections.snowflake]
account = "synergy.eu-west-1"
user = "BMEGDOUD@SYNERGY.FR"
password = "Azert2609*"
role = "DEMODB_GEO_ADM"
warehouse = "WH_CONSULTANT"
database = "DEMODB"
schema = "VENTES"
client_session_keep_alive = true
