OPENAI_API_KEY="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"
OPENAI_ASSISTANT_ID="asst_AAUXjO2r6idtVcIRejd6OkZb"
MAPBOX_TOKEN="pk.eyJ1IjoiYm1lZ2RvdWQiLCJhIjoiY2xuanpyd3l2MGljODJpcDJleWdzZGo0YyJ9.98itq-HdV3XiTvQ2_oP2rA"
