AI="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"
ASSISTANT="asst_AAUXjO2r6idtVcIRejd6OkZb"
MAPBOX_TOKEN="pk.eyJ1IjoiYm1lZ2RvdWQiLCJhIjoiY2xuanpyd3l2MGljODJpcDJleWdzZGo0YyJ9.98itq-HdV3XiTvQ2_oP2rA"
