OPENAI_API_KEY="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"
OPENAI_ASSISTANT_ID="asst_AAUXjO2r6idtVcIRejd6OkZb"
MAPBOX_TOKEN="pk.eyJ1IjoiYm1lZ2RvdWQiLCJhIjoiY2xuanpyd3l2MGljODJpcDJleWdzZGo0YyJ9.98itq-HdV3XiTvQ2_oP2rA"
